// <auto-generated />
using CodeFirstConvention;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstConvention.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250410151029_Creation-Initiale")]
    partial class CreationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CodeFirstConvention.Automobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FabricantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FabricantId");

                    b.ToTable("Automobiles");
                });

            modelBuilder.Entity("CodeFirstConvention.Fabricant", b =>
                {
                    b.Property<int>("FabricantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnneeCreation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaysId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FabricantId");

                    b.HasIndex("PaysId");

                    b.ToTable("Fabricants");
                });

            modelBuilder.Entity("CodeFirstConvention.Pays", b =>
                {
                    b.Property<int>("PaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaysId");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("CodeFirstConvention.Automobile", b =>
                {
                    b.HasOne("CodeFirstConvention.Fabricant", "Fabricant")
                        .WithMany("Automobiles")
                        .HasForeignKey("FabricantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricant");
                });

            modelBuilder.Entity("CodeFirstConvention.Fabricant", b =>
                {
                    b.HasOne("CodeFirstConvention.Pays", "Pays")
                        .WithMany("Fabricants")
                        .HasForeignKey("PaysId");

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("CodeFirstConvention.Fabricant", b =>
                {
                    b.Navigation("Automobiles");
                });

            modelBuilder.Entity("CodeFirstConvention.Pays", b =>
                {
                    b.Navigation("Fabricants");
                });
#pragma warning restore 612, 618
        }
    }
}
